<a href="https://colab.research.google.com/github/ringgoagsya/latihan_python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NumPy

Untuk mengimport numpy dan mengecek versi numpy yang digunakan dapat dengan kodingan dibawah

In [ ]:
import numpy
numpy.__version__

'1.19.5'

terlihat dari output diatas kita menggunakan numpy versi 1.19.5. ini dapat berbeda di setiap device yang digunakan, sehubungan kita menggunakan google collab maka akan sama.

In [ ]:
import numpy as np

kita juga bisa meginport numpy dengan alias (as) untuk mempersingkat penulisan kodingan nantikknya menjadi np. yang biasanya numpy.array() menjadi np.array(). Simple kan :)

## Reminder about Built In Documentation


untuk menampilkan semua konten namespace numpy, Anda dapat mengetik in

In [ ]:
np.<TAB>

SyntaxError: ignored

untuk menampilkan about atau documentasi dari numpy bisa dengan mengetik kodingan dibawah ini

In [ ]:
np?

# Understanding Data Types in Python

Bagian ini menjelaskan dan membandingkan bagaimana array menggunakan Python itu sendiri, dan bagaimana pula dengan numpy.

Dalam kodingan C biasa seperti dibawah ini

```C
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

Sementara di Python, operasi yang setara dan singkat dapat ditulis seperti dibawah ini

In [ ]:
# Python code
result = 0
for i in range(100):
    result += i

Dalam python tidak perlu mengidentifikasi tipe data yang digunakan karena python sudah bisa mengenali secara otomatis.

In [ ]:
# Python code
x = 4
x = "four"

sedangkan dalam C kita perlu menginisialisasi tipe datanya jika kita input tidak sesuai dengan tipe datanya maka akan eror seperti contoh di bawah ini:

```C
/* C code */
int x = 4;
x = "four";  // FAILS
```

itulah yang membuat python lebih simple dan fleksibel dengan keadaan hiyaa :)

## A Python Integer Is More Than Just an Integer

Integer di python tidak perlu di tuliskan seperti halnya bahasa C dibawah. sehingga python bisa mengidentifikasi nya sebagai objek

```C
struct _longobject {
    long ob_refcnt;
    PyTypeObject *ob_type;
    size_t ob_size;
    long ob_digit[1];
};
```

Integer di Python 3.4 sebenarnya berisi empat bagian:

1. ob_refcnt, jumlah referensi yang membantu Python menangani alokasi memori dan deallocation memori secara diam"
2. ob_type, yang mengkodekan tipe variabel
3. ob_size, yang menentukan ukuran data
ob_digit, yang berisi nilai integer aktual yang kita harapkan oleh variabel python

Ini menunjukkan beberapa kelebihan dalam menyimpan integer dengan Python dibandingkan dengan integer dalam bahasa yang dikompilasi seperti C.

## A Python List Is More Than Just a List

Berikut penulisan kodingan list pada python. bawaan python ya belum lagi dari numpy

In [ ]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

di kodingan diatas kita list dengan range 10

In [ ]:
type(L[0])

int

untuk melihat type data dari list index ke-0 bisa dengan kodingan diatas dapat dilihat typenya yaitu int (integer)

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

dengan fungsi str kita bisa memasukkan data list L tadi ke variabel c diatas. apa bila kita kita menginisialisasi sebagai string maka penandanya yaitu di output akan ditulis dalam tanda kutip

In [ ]:
type(L2[0])

str

kan type datanya sudah berubah menjadi str(string)

Karena pengkodean yang dinamis. Python dapat membuat daftar yang heterogen seperti dibawah ini :

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

untul type data L3[0] -> bool atau boolean yang mengembalikan nilai true atau false. L3[1] -> str atau string karena dalam penulisan didalam tanda kutip. L3[2] -> float dalam penginisialisasi berkoma, dan L3[3] -> int atau integer sebagai bil bulat

## Fixed-Type Arrays in Python

Penjelasan tentang array bawaan (tersedia sejak Python versi 3.3). Kodingan digunakan untuk membuat array dengan tipe seragam seperti dibawah ini :

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

'i' disini adalah kode tipe yang menunjukkan isinya adalah bilangan bulat.

In [ ]:
import numpy as np

kode diatas untuk mengimport library numpy dengan alias (as) np untuk mempersingkat pengkodean

## Creating Arrays from Python Lists

penggunaan ``np.array`` untuk membuat array list dari library numpy :

In [ ]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

beda dengan list python biasa, Numpy dibatasi dengan array dengan tipe yang sama. Jika tidak cocok maka numpy akan meng upcast jika memungkinkan . contoh dibawah ono ada 1 angak float maka semuanya dijakian float sama si numpy:

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

kita juga bisa mengatur tipe datanya dengan key ``dtype`` seperti d bawah ini:

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

salah sati cara menginisialisasi array multidimensi menggunakan list dari list wkwkw

In [ ]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

membuat array berskala besar

In [ ]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

dari kodigan  diatas untuk membuat array bernilai 0 dengan type data int

In [ ]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

kodingan diatas untuk membuat array bernilai 1 ukuran 3x5 dengan tipe data float

In [ ]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

np.full untuk membuat array berapa kali berapa dengan inisialiasi angka lain

In [ ]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

membuat array dengan urutan linier dimulai dari 0 dan berakhir sebelum 20 dengan menambah 2 angka.

In [ ]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

membuat array dengan jarak yang sama antara 0 dan 1 sebanyak 5 data.

In [ ]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.50370207, 0.07412198, 0.59958168],
       [0.75458175, 0.79084841, 0.83434284],
       [0.62874081, 0.67623731, 0.12515995]])

membuat array 3x3 dengan nilai random bisa dengan kodingn diatas

In [ ]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.31494728,  0.39158822, -0.21010945],
       [ 0.12347776,  1.29075796, -0.34006098],
       [-0.5586614 ,  0.43623774, -0.5086171 ]])

membuat array 3x3 dengan nilai random terdistribusi normal dimana kita se mean nya 0 dan standart deviasinya 1

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 4, 2],
       [3, 0, 0],
       [2, 0, 3]])

np.random.randint(0, 10, (3, 3)) untuk membuat array 3x3 dengan random inteher dengan interval 0 sampai 10

In [ ]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.eye untuk membuat matrik indentitas yaitu diagonal nya bernilai 1. adapun cara lain membuat matrik identitas yaitu :

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

menggunakan np.identity juga bisa membuat matrix identitas

In [ ]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

membuat array tiga bilangan bulat yang tidak diinisialisasi
Nilai akan menjadi apa pun yang terjadi sudah ada di lokasi memori itu

## NumPy Standard Data Types

Array NumPy berisi nilai dari satu tipe, jadi penting untuk memiliki pengetahuan mendetail tentang tipe tersebut dan batasannya

In [ ]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

dari diatas bisa kita inisialisasi tipe data dengan dtype=''. atau bisa juga dtype=np.int16 seperti dibawha ini

In [ ]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Atau bisa juga dilihat type data pada np. atau python

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

# The Basics of NumPy Arrays

Manipulasi data dengan Python hampir identik dengan manipulasi array NumPy

pada materi ini akan dibahas beberapa kategori manipulasi array dasar di sini:

Atribut array: Menentukan ukuran, bentuk, konsumsi memori, dan tipe data array
Pengindeksan array: Mendapatkan dan mengatur nilai elemen array individu
Mengiris array: Mendapatkan dan mengatur subarray yang lebih kecil dalam array yang lebih besar
Pembentukan ulang larik: Mengubah bentuk larik tertentu
Menggabungkan dan memisahkan array: Menggabungkan beberapa array menjadi satu, dan memisahkan satu array menjadi banyak

## NumPy Array Attributes

membuat 3 buah jenis array dari 1 dimensi, 2 dimensi dan 3 dimensi. kemudian kita lihat apa saja atribut didalam nya

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

print("array 1 dimensi\n",x1)
print("array 2 dimensi\n",x2)
print("array 3 dimensi \n",x3)

array 1 dimensi
 [5 0 3 3 7 9]
array 2 dimensi
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
array 3 dimensi 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


setiap array memeliki beberapa atribut ``ndim`` (jumlah dimensi), ``shape`` (ukuran setiap dimensi), and ``size`` (ukuran total dari array tersebut):

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


fungsi``dtype``, untuk mengecek type data dari array tsbt

In [ ]:
print("dtype:", x3.dtype)

dtype: int64


atribut lain spt ``itemsize``, akan menampilkan ukuran aray (dalam bytes), dan ``nbytes``, memuat ukuran total dalam byte dari array:

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## Array Indexing: Accessing Single Elements

setiap array pengindeksan nya tetap dimulai dari index-0. bisa dilihat dari output beberpa contoh dibawah

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0]

5

In [ ]:
x1[4]

7

untuk mengindeks dari akhir array bisa dimulai dengan negatif -1

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

di array multidimensi untuk pengindeksan tupel dipisahkan dengan koma

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0, 0]

3

untuk x2[0,0] artinya array dari baris berindeks 0 dan kolom berindeks 0

In [ ]:
x2[2, 0]

1

untuk x2[2,0] artinya array dari baris berindeks 2 dan kolom berindeks 0

In [ ]:
x2[2, -1]

7

untuk x2[2,-1] artinya array dari baris berindeks 2 dan kolom berindeks -1. indek -1 disini berarti array dengan indek terakhir.

bisa juga mengubah nilai array dengan cara menulis array keberapa dan dilanjutkan dengan = + berapa nilainya. seperti dibawha ini

In [ ]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

jika kita mengubah nilai tetapi nilai yang kita masukkan tidak sesuai dengan type data sebelumnya. maka aka di truncated menjadi tipe data sebelumnya. misal tipe data sebelumnya int dan kita mengubah salah satu nilai menjadi bilangan berkoma maka nilai berkoma akan dijadikan bilangan bulat dengan algoritma pembulatan normal.

In [ ]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

kita juga bisa mengakses elemen array dengan notasi  *slice* , atau tanda colon (``:``).
penjelasan slice akan dijelaskan seperti dibawah ini
``` python
x[start:stop:step]
```
Jika salah satu di antaranya tidak ditentukan, nilai defaultnya start = 0, stop = ukuran dimensi, step = 1. Kita akan melihat mengakses sub-array dalam satu dimensi dan dalam beberapa dimensi.

### One-dimensional subarrays

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

membuat array berjumlah 10 sesuai urutan

In [ ]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

kodingan diatas untuk mengabil 5 buah data pertama dari array

In [ ]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

kodingan diatas untuk mengabil 5 buah data terakhir dari array

In [ ]:
x[4:7]  # middle sub-array

array([4, 5, 6])

kodingan diatas untuk mengabil nilai dengan index awal yaitu 4 dan batas sebelum index ke -7 yaitu sampai index ke -6

In [ ]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

mengabil setiap elemen dengan awal index ke 0 dan langkah 2 dan diakhiri sampai index terakhir

In [ ]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

mengambil element awal index 1 kemudian step nya 2 sampai habis

Kasus yang berpotensi membingungkan adalah ketika nilai `` step ``  negatif.
Dalam hal ini, default untuk `` start ``dan `` stop `` ditukar.
Ini menjadi cara mudah untuk membalikkan array:

In [ ]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

dibalik satu sama lain dari indeks 5 dan stepnya 2

### Multi-dimensional subarrays

Multi-dimensional slices bekerja dengan cara yang sama, dengan beberapa slice dipisahkan oleh koma. Sebagai contoh:

In [ ]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

untuk mengambil array dengan 2x3

In [ ]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

untuk mengambil array 3 x 2:

In [ ]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Dimensi subarray dapat dibalik bersama:

In [ ]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

Ini dapat dilakukan dengan menggabungkan pengindeksan dan slice, menggunakan slice kosong yang ditandai dengan satu titik dua (``:``):

mengambil kolom pertama dari x2

In [ ]:
print(x2[:, 0])  # first column of x2

[12  7  1]


mengambil baris pertama array x2

In [ ]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


dalam kasus akses baris, potongan kosong dapat dihilangkan untuk sintaks yang lebih ringkas:

In [ ]:
print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

Satu hal penting untuk diketahui tentang slicing array adalah bahwa numpy akan mengembalikan tampilan dari salinan data array. Ini adalah satu area di mana pengirisan array NumPy berbeda dari pengirisan daftar Python: dalam list, slice akan menjadi salinan. 

In [ ]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


kita akan mengambil array 2x2 dari array x2 diatas

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


kita coba ganti index [0,0] menjadi 99 maka akan menjadi seperti dibawah ini

In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


ini akan berefek kepada array kita sebelum kita mengabil yang 2x2

### Creating copies of arrays

untuk menyalin ke variabel yang lain kita bisa mengguakan syntax ``copy()``. Supaya data sebelumnnya tidak terkena efek ketika kita menmodivikasi nantiknya seperti dibawah ini

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


nah setelah kita modifikasi subbarray nya. array aslinya yang awal tidak akan termodivikasi, coba kita coba di bawah ini mengubah array index [0,0] menjadi 42

In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


disini subbarray kita sudah diubah, coba kita cek array awal tadi.

In [ ]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


maka array awal tadi tidak akan termodifikasi

## Reshaping of Arrays

Reshaping of array atau pembentukan kembali dari array.
dengan fungsi ``reshape`` .
Misalnya, jika Anda ingin memasukkan angka 1 hingga 9 dalam array 3 × 3, Anda dapat melakukan hal berikut:

In [ ]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


beriku cara penggunaan fungsi ``reshape`` untuk mengatu atau pembetukan kembali dari array yang sudah dibuat.

pertama kita melakukan ``reshape`` kemudian menggunakan keyword ``newaxis`` dengan menggunakan methodh slice dalam pembentukan seperti kodingan dibawah ini

In [ ]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [ ]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

Semua rutinitas sebelumnya bekerja pada single array. Ini juga memungkinkan untuk menggabungkan beberapa array menjadi satu, dan sebaliknya membagi single array  menjadi multiple array. 

### Concatenation of arrays

Concatenation adalah penggabungan 2 arrays di NumPy,dengan fungsi ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` menggunakan tuple atau list array sebagai argumen pertamanya, seperti yang bisa kita lihat di sini:

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Anda juga dapat menggabungkan lebih dari dua array sekaligus:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


Ini juga dapat digunakan untuk array dua dimensi:

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Untuk bekerja dengan array dengan dimensi campuran, akan lebih jelas jika menggunakan fungsi ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) :

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

menggunakan fungsi ``np.dstack`` akan menumpuk array di sepanjang sumbu ketiga.

### Splitting of arrays

Kebalikan dari penggabungan adalah pemisahan, yang diimplementasikan oleh fungsi ``np.split``, ``np.hsplit``, and ``np.vsplit``.  Untuk masing-masing ini, kita dapat memberikan daftar indeks yang memberikan poin perpecahan:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Perhatikan bahwa * N * titik pisah, mengarah ke * N + 1 * subarray.
Fungsi terkait `` np.hsplit`` dan `` np.vsplit`` serupa:

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


dengan fungsi ``np.dsplit``kan membagi array di sepanjang sumbu ketiga.

# Computation on NumPy Arrays: Universal Functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world.
Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

## The Slowness of Loops

Python's default implementation (known as CPython) does some operations very slowly.
This is in part due to the dynamic, interpreted nature of the language: the fact that types are flexible, so that sequences of operations cannot be compiled down to efficient machine code as in languages like C and Fortran.
Recently there have been various attempts to address this weakness: well-known examples are the [PyPy](http://pypy.org/) project, a just-in-time compiled implementation of Python; the [Cython](http://cython.org) project, which converts Python code to compilable C code; and the [Numba](http://numba.pydata.org/) project, which converts snippets of Python code to fast LLVM bytecode.
Each of these has its strengths and weaknesses, but it is safe to say that none of the three approaches has yet surpassed the reach and popularity of the standard CPython engine.

The relative sluggishness of Python generally manifests itself in situations where many small operations are being repeated – for instance looping over arrays to operate on each element.
For example, imagine we have an array of values and we'd like to compute the reciprocal of each.
A straightforward approach might look like this:

In [ ]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

This implementation probably feels fairly natural to someone from, say, a C or Java background.
But if we measure the execution time of this code for a large input, we see that this operation is very slow, perhaps surprisingly so!
We'll benchmark this with IPython's ``%timeit`` magic (discussed in [Profiling and Timing Code](01.07-Timing-and-Profiling.ipynb)):

In [ ]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1 loop, best of 5: 2.33 s per loop


It takes several seconds to compute these million operations and to store the result!
When even cell phones have processing speeds measured in Giga-FLOPS (i.e., billions of numerical operations per second), this seems almost absurdly slow.
It turns out that the bottleneck here is not the operations themselves, but the type-checking and function dispatches that CPython must do at each cycle of the loop.
Each time the reciprocal is computed, Python first examines the object's type and does a dynamic lookup of the correct function to use for that type.
If we were working in compiled code instead, this type specification would be known before the code executes and the result could be computed much more efficiently.

## Introducing UFuncs

For many types of operations, NumPy provides a convenient interface into just this kind of statically typed, compiled routine. This is known as a *vectorized* operation.
This can be accomplished by simply performing an operation on the array, which will then be applied to each element.
This vectorized approach is designed to push the loop into the compiled layer that underlies NumPy, leading to much faster execution.

Compare the results of the following two:

In [ ]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


Looking at the execution time for our big array, we see that it completes orders of magnitude faster than the Python loop:

In [ ]:
%timeit (1.0 / big_array)

1000 loops, best of 5: 1.67 ms per loop


Vectorized operations in NumPy are implemented via *ufuncs*, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.
Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

In [ ]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [ ]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Computations using vectorization through ufuncs are nearly always more efficient than their counterpart implemented using Python loops, especially as the arrays grow in size.
Any time you see such a loop in a Python script, you should consider whether it can be replaced with a vectorized expression.

## Exploring NumPy's UFuncs

Ufuncs exist in two flavors: *unary ufuncs*, which operate on a single input, and *binary ufuncs*, which operate on two inputs.
We'll see examples of both these types of functions here.

### Array arithmetic

NumPy's ufuncs feel very natural to use because they make use of Python's native arithmetic operators.
The standard addition, subtraction, multiplication, and division can all be used:

In [ ]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ``**`` operator for exponentiation, and a ``%`` operator for modulus:

In [ ]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [ ]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the ``+`` operator is a wrapper for the ``add`` function:

In [ ]:
np.add(x, 2)

array([2, 3, 4, 5])

The following table lists the arithmetic operators implemented in NumPy:

| Operator	    | Equivalent ufunc    | Description                           |
|---------------|---------------------|---------------------------------------|
|``+``          |``np.add``           |Addition (e.g., ``1 + 1 = 2``)         |
|``-``          |``np.subtract``      |Subtraction (e.g., ``3 - 2 = 1``)      |
|``-``          |``np.negative``      |Unary negation (e.g., ``-2``)          |
|``*``          |``np.multiply``      |Multiplication (e.g., ``2 * 3 = 6``)   |
|``/``          |``np.divide``        |Division (e.g., ``3 / 2 = 1.5``)       |
|``//``         |``np.floor_divide``  |Floor division (e.g., ``3 // 2 = 1``)  |
|``**``         |``np.power``         |Exponentiation (e.g., ``2 ** 3 = 8``)  |
|``%``          |``np.mod``           |Modulus/remainder (e.g., ``9 % 4 = 1``)|

Additionally there are Boolean/bitwise operators; we will explore these in [Comparisons, Masks, and Boolean Logic](02.06-Boolean-Arrays-and-Masks.ipynb).

### Absolute value

Just as NumPy understands Python's built-in arithmetic operators, it also understands Python's built-in absolute value function:

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

The corresponding NumPy ufunc is ``np.absolute``, which is also available under the alias ``np.abs``:

In [ ]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [ ]:
np.abs(x)

array([2, 1, 0, 1, 2])

This ufunc can also handle complex data, in which the absolute value returns the magnitude:

In [ ]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions

NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions.
We'll start by defining an array of angles:

In [ ]:
theta = np.linspace(0, np.pi, 3)

Now we can compute some trigonometric functions on these values:

In [ ]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


The values are computed to within machine precision, which is why values that should be zero do not always hit exactly zero.
Inverse trigonometric functions are also available:

In [ ]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

Another common type of operation available in a NumPy ufunc are the exponentials:

In [ ]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


The inverse of the exponentials, the logarithms, are also available.
The basic ``np.log`` gives the natural logarithm; if you prefer to compute the base-2 logarithm or the base-10 logarithm, these are available as well:

In [ ]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


There are also some specialized versions that are useful for maintaining precision with very small input:

In [ ]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


When ``x`` is very small, these functions give more precise values than if the raw ``np.log`` or ``np.exp`` were to be used.

### Specialized ufuncs

NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more.
A look through the NumPy documentation reveals a lot of interesting functionality.

Another excellent source for more specialized and obscure ufuncs is the submodule ``scipy.special``.
If you want to compute some obscure mathematical function on your data, chances are it is implemented in ``scipy.special``.
There are far too many functions to list them all, but the following snippet shows a couple that might come up in a statistics context:

In [ ]:
from scipy import special

In [ ]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [ ]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


There are many, many more ufuncs available in both NumPy and ``scipy.special``.
Because the documentation of these packages is available online, a web search along the lines of "gamma function python" will generally find the relevant information.

## Advanced Ufunc Features

Many NumPy users make use of ufuncs without ever learning their full set of features.
We'll outline a few specialized features of ufuncs here.

### Specifying output

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored.
Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be.
For all ufuncs, this can be done using the ``out`` argument of the function:

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


This can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:

In [ ]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


If we had instead written ``y[::2] = 2 ** x``, this would have resulted in the creation of a temporary array to hold the results of ``2 ** x``, followed by a second operation copying those values into the ``y`` array.
This doesn't make much of a difference for such a small computation, but for very large arrays the memory savings from careful use of the ``out`` argument can be significant.

### Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object.
For example, if we'd like to *reduce* an array with a particular operation, we can use the ``reduce`` method of any ufunc.
A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling ``reduce`` on the ``add`` ufunc returns the sum of all elements in the array:

In [ ]:
x = np.arange(1, 6)
np.add.reduce(x)

15

Similarly, calling ``reduce`` on the ``multiply`` ufunc results in the product of all array elements:

In [ ]:
np.multiply.reduce(x)

120

If we'd like to store all the intermediate results of the computation, we can instead use ``accumulate``:

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Note that for these particular cases, there are dedicated NumPy functions to compute the results (``np.sum``, ``np.prod``, ``np.cumsum``, ``np.cumprod``), which we'll explore in [Aggregations: Min, Max, and Everything In Between](02.04-Computation-on-arrays-aggregates.ipynb).

### Outer products

Finally, any ufunc can compute the output of all pairs of two different inputs using the ``outer`` method.
This allows you, in one line, to do things like create a multiplication table:

In [ ]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

The ``ufunc.at`` and ``ufunc.reduceat`` methods, which we'll explore in [Fancy Indexing](02.07-Fancy-Indexing.ipynb), are very helpful as well.

Another extremely useful feature of ufuncs is the ability to operate between arrays of different sizes and shapes, a set of operations known as *broadcasting*.
This subject is important enough that we will devote a whole section to it (see [Computation on Arrays: Broadcasting](02.05-Computation-on-arrays-broadcasting.ipynb)).

## Ufuncs: Learning More

More information on universal functions (including the full list of available functions) can be found on the [NumPy](http://www.numpy.org) and [SciPy](http://www.scipy.org) documentation websites.

Recall that you can also access information directly from within IPython by importing the packages and using IPython's tab-completion and help (``?``) functionality, as described in [Help and Documentation in IPython](01.01-Help-And-Documentation.ipynb).

<!--NAVIGATION-->
< [The Basics of NumPy Arrays](02.02-The-Basics-Of-NumPy-Arrays.ipynb) | [Contents](Index.ipynb) | [Aggregations: Min, Max, and Everything In Between](02.04-Computation-on-arrays-aggregates.ipynb) >

<a href="https://colab.research.google.com/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/02.03-Computation-on-arrays-ufuncs.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory"></a>
